services:
  mariadb:
    build: ./mariadb
    image: mariadb_inception:test
    container_name: mariadb_inception
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - mdb_vol:/var/lib/mysql
    networks:
      - test_net

  wordpress:
    depends_on:
      - mariadb
    build: ./wordpress
    image: wordpress_inception:test
    container_name: wordpress_inception
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - wp_vol:/var/www/html/paugonca.42.fr/
    networks:
      - test_net

  nginx:
    depends_on:
      - wordpress
    build: ./nginx
    image: nginx_inception:test
    container_name: nginx_inception
    ports:
            - "443:443"
    volumes:
      - wp_vol:/var/www/html/paugonca.42.fr/
    networks:
      - test_net

volumes:
  wp_vol:
    name: wp_vol
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/paugonca/Docker_volumes/wordpress_volume

  mdb_vol:
    name: mdb_vol
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/paugonca/Docker_volumes/mariadb_volume

networks:
  test_net:
    driver: bridge
